version: "3.8" # Compose file format version

services:
  app: # WordPress application service
    image: wordpress:php8.1-apache
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend # Connect to the backend Docker network
  db: # MySQL database service
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /mnt/docker/db:/var/lib/mysql #bind mount to LVM-backed volume
    networks:
      - backend # Connect to the backend Docker network

  haproxy: # Load balancer service
    image: haproxy:alpine
    ports:
      - "8080:8080"  # Expose HAProxy on host port 8080
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app # Ensure the WordPress app starts before HAProxy
    networks:
      - backend

networks:
  backend: # Define shared user-defined bridge network